### ISSUE TITLE
Connection between E-Ink and PI Zero

### ISSUE THREAD

**Issue by bernb** [rec0de/vsmp-zero#1]
How did you connect the E-Ink to the PI Zero? I struggle to find a manual as everything seems to be made for the normal RPI.
I got this one from Waveshare
E-Ink: https://www.waveshare.com/7.8inch-e-paper-hat.htm
RPI Zero: https://www.waveshare.com/raspberry-pi-zero.htm

PS.: I believe I need to attach GPIO headers or buy a RPI that has pre-soldered GPIO headers?

**Comment by rec0de** [comment]
Hi bernb!
I personally used a Pi with pre-soldered headers but that's not required as long as you're comfortable with some basic soldering.
The E-Ink HAT comes with an alternative connection cable (broad white connector with 8 colourful jumper wires coming out). That connector fits into the white socket on the underside of the HAT, and it has all connections necessary to use the it (labeled 5V, GND, MISO, MOSI, ...). You just need to connect the other end of the cable to the matching RPI pins somehow.

You can check which pins to connect to at the [Waveshare Wiki](https://www.waveshare.com/wiki/7.8inch_e-Paper_HAT), there's a table under the heading _Working with Raspberry Pi_.

Hope that helps!
