### ISSUE TITLE
Display flashes but then nothing happens

### ISSUE THREAD

**Issue by bernb** [rec0de/vsmp-zero#2]
PS.: I was a bit early with my question. I got it solved by setting
```
#define LIGHSENSE 0
#define HWACCEL 0
```
Everything is now working as intended! Thanks for you awesome project :-).
I would like to suggest to set defaults a bit more defensive i.e. deactivating lightsense and hardware acceleration by default.

Original Post:
---

I got every working so far, following closely your readme. vsmp gets compiled and I am able to start it:
```
$ sudo ./vsmp ../out.mkv 1
IT8951 initialized
FFmpeg init done
Display cleared
```
Dhe E-Ink Paper flashes black two times, but then nothing more happens. If you could provide some ideas how to debug this it would be highly appreciated! 
For testing I have set
```
#define FRAMES_PER_HOUR 600
#define FRAME_STEP_SIZE 10
```
E-Ink product I use: "1872×1404, 7.8inch E-Ink display HAT for Raspberry Pi"
I use this file as sample: https://filesamples.com/formats/mkv (1080p)

**Comment by rec0de** [comment]
Cool, glad to hear you got it to work!
I agree on the settings thing - currently these are just the settings I use, but I think it'd make sense to change that to something more minimal.
